version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: gc_enterprise_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - gc_enterprise_network

  adminer:
    image: adminer:latest
    container_name: gc_enterprise_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - gc_enterprise_network

networks:
  gc_enterprise_network:
    driver: bridge

volumes:
  mariadb_data: