# Generated by Django 5.1.1 on 2024-10-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='hourly_rate',
        ),
    ]
