# Generated by Django 5.1.1 on 2024-10-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankdetails',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='company.company'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='company.company'),
        ),
    ]
