# Generated by Django 5.1.1 on 2024-10-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companybankdetails_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyBankDetails',
            new_name='Bank',
        ),
    ]
