# Generated by Django 5.1.1 on 2024-10-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_companybankdetails_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name',
            new_name='name',
        ),
    ]
