# Generated by Django 5.1.1 on 2024-11-24 10:45

import company.models
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_bank_created_at_bank_created_by_bank_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Bank', 'verbose_name_plural': 'Banken'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmen'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Ansprechpartner', 'verbose_name_plural': 'Ansprechpartner'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
        migrations.AddField(
            model_name='company',
            name='court',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gericht'),
        ),
        migrations.AddField(
            model_name='company',
            name='court_register',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Handelsregister'),
        ),
        migrations.AddField(
            model_name='company',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Faxnummer'),
        ),
        migrations.AddField(
            model_name='company',
            name='prefix',
            field=models.CharField(blank=True, help_text="Beispiel: 'W-' für 'W-xxxxxxx'", max_length=5, null=True, verbose_name='Auftragsnummer-Präfix'),
        ),
        migrations.AddField(
            model_name='company',
            name='suffix',
            field=models.CharField(blank=True, help_text="Beispiel: '-XYZ' für  'xxxxxxx-XYZ'", max_length=5, null=True, verbose_name='Auftragsnummer-Suffix'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bic',
            field=models.CharField(max_length=11, verbose_name='BIC/SWIFT'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='company.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='iban',
            field=models.CharField(max_length=34, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Bankname'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.contact', verbose_name='Ansprechpartner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/company_logos/', validators=[company.models.validate_image_extension], verbose_name='Firmenlogo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Firmenname'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_id',
            field=models.CharField(max_length=50, verbose_name='USt-IdNr.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Webseite'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='company.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(max_length=100, verbose_name='Plattform'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='HistoricalBank',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=11, verbose_name='BIC/SWIFT')),
                ('name', models.CharField(max_length=100, verbose_name='Bankname')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Firma')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'historical Bank',
                'verbose_name_plural': 'historical Banken',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=255, verbose_name='Firmenname')),
                ('vat_id', models.CharField(max_length=50, verbose_name='USt-IdNr.')),
                ('court_register', models.CharField(blank=True, max_length=50, null=True, verbose_name='Handelsregister')),
                ('court', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gericht')),
                ('street', models.CharField(max_length=255, verbose_name='Straße')),
                ('postal_code', models.CharField(max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('country', models.CharField(max_length=100, verbose_name='Land')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefonnummer')),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Faxnummer')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Webseite')),
                ('logo', models.TextField(blank=True, max_length=100, null=True, validators=[company.models.validate_image_extension], verbose_name='Firmenlogo')),
                ('prefix', models.CharField(blank=True, help_text="Beispiel: 'W-' für 'W-xxxxxxx'", max_length=5, null=True, verbose_name='Auftragsnummer-Präfix')),
                ('suffix', models.CharField(blank=True, help_text="Beispiel: '-XYZ' für  'xxxxxxx-XYZ'", max_length=5, null=True, verbose_name='Auftragsnummer-Suffix')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contact_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.contact', verbose_name='Ansprechpartner')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'historical Firma',
                'verbose_name_plural': 'historical Firmen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('role', models.CharField(max_length=100, verbose_name='Rolle')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefonnummer')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'historical Ansprechpartner',
                'verbose_name_plural': 'historical Ansprechpartner',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrderCounter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Zähler')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Firma')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'historical Auftragszähler',
                'verbose_name_plural': 'historical Auftragszähler',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSocialMedia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am')),
                ('platform', models.CharField(max_length=100, verbose_name='Plattform')),
                ('url', models.URLField(verbose_name='URL')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Firma')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'historical Social Media',
                'verbose_name_plural': 'historical Social Media',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert am')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Zähler')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Firma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Auftragszähler',
                'verbose_name_plural': 'Auftragszähler',
                'unique_together': {('company', 'year')},
            },
        ),
    ]
