# Generated by Django 5.1.1 on 2024-11-25 09:52

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_bank_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='company/company_logos/', validators=[company.models.validate_image_extension], verbose_name='Unterschriftenbild'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='signature',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[company.models.validate_image_extension], verbose_name='Unterschriftenbild'),
        ),
    ]
