# Generated by Django 5.1.1 on 2024-09-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
