# Generated by Django 5.1.1 on 2024-09-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='created', max_length=20)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='DocumentType',
            new_name='OrderType',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.ordertype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.task'),
        ),
    ]
