# Generated by Django 5.1.1 on 2024-09-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.DeleteModel(
            name='DocumentHistory',
        ),
    ]
