# Generated by Django 5.1.1 on 2024-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_document_document_type_delete_documenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
