# Generated by Django 5.1.1 on 2024-10-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_document_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=6),
            preserve_default=False,
        ),
    ]
