# Generated by Django 5.1.1 on 2024-10-01 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Aufgaben Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_tasks', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='tasks',
            field=models.ManyToManyField(related_name='orders', to='orders.task'),
        ),
    ]
