# Generated by Django 5.1.1 on 2024-10-04 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_vat_task_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='vat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vat',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
