# Generated by Django 5.1.1 on 2024-10-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_vat_created_at_vat_is_default_vat_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
