# Generated by Django 5.1.1 on 2024-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nr',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
