# Generated by Django 5.1.1 on 2024-11-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_order_type_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Einleitung'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Einleitung'),
        ),
    ]
