# Generated by Django 5.1.1 on 2024-11-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_document_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Einleitung'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Einleitung'),
        ),
    ]
