# Generated by Django 5.1.1 on 2024-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_document_introduction_and_more'),
    ]

    operations = [
    ]
