# Generated by Django 5.1.1 on 2024-11-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_document_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Abschluss'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Abschluss'),
        ),
    ]
