# Generated by Django 5.1.1 on 2024-11-26 08:43

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_document_conclusion_historicaldocument_conclusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltaskposition',
            old_name='date',
            new_name='task_position_date',
        ),
        migrations.RenameField(
            model_name='taskposition',
            old_name='date',
            new_name='task_position_date',
        ),
        migrations.AlterField(
            model_name='document',
            name='introduction',
            field=models.TextField(blank=True, default=orders.models.default_introduction, null=True, verbose_name='Einleitung'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='introduction',
            field=models.TextField(blank=True, default=orders.models.default_introduction, null=True, verbose_name='Einleitung'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung (Intern)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung (Intern)'),
        ),
    ]
